export function useOrganizations() {
    const organizations = [
        { label: 'Red Cross', value: 'Red Cross' },
        { label: 'UNICEF', value: 'UNICEF' },
        { label: 'Doctors Without Borders', value: 'Doctors Without Borders' },
        { label: 'World Wildlife Fund', value: 'World Wildlife Fund' },
        { label: 'Habitat for Humanity', value: 'Habitat for Humanity' },
        { label: 'The Salvation Army', value: 'The Salvation Army' },
        { label: 'American Cancer Society', value: 'American Cancer Society' },
        { label: 'American Red Cross', value: 'American Red Cross' },
        { label: 'Oxfam', value: 'Oxfam' },
        { label: 'UNICEF USA', value: 'UNICEF USA' },
        { label: 'World Food Programme', value: 'World Food Programme' },
        { label: 'ShelterBox', value: 'ShelterBox' },
        {
            label: 'ICRC - International Committee of the Red Cross',
            value: 'ICRC',
        },
        {
            label: 'MSF - Médecins Sans Frontières',
            value: 'Médecins Sans Frontières',
        },
        { label: 'UNHCR', value: 'UNHCR' },
        { label: 'CARE International', value: 'CARE International' },
        { label: 'World Vision', value: 'World Vision' },
        { label: 'Save the Children', value: 'Save the Children' },
        { label: 'Feed the Children', value: 'Feed the Children' },
        { label: 'Operation USA', value: 'Operation USA' },
        { label: 'Direct Relief', value: 'Direct Relief' },
        { label: 'Global Giving', value: 'Global Giving' },
        { label: 'Kiva', value: 'Kiva' },
        { label: 'DonorsChoose', value: 'DonorsChoose' },
        { label: 'Charity Water', value: 'Charity Water' },
        { label: 'Room to Read', value: 'Room to Read' },
        { label: 'Heifer International', value: 'Heifer International' },
        { label: 'Action Against Hunger', value: 'Action Against Hunger' },
        { label: ' Mercy Corps', value: 'Mercy Corps' },
        { label: 'Tearfund', value: 'Tearfund' },
        { label: "Samaritan's Purse", value: "Samaritan's Purse" },
        {
            label: 'International Rescue Committee',
            value: 'International Rescue Committee',
        },
        { label: 'Plan International', value: 'Plan International' },
        { label: 'PETA', value: 'PETA' },
        { label: 'Humane Society', value: 'Humane Society' },
        { label: 'ASPCA', value: 'ASPCA' },
        { label: 'Make-A-Wish Foundation', value: 'Make-A-Wish Foundation' },
        {
            label: "St. Jude Children's Research Hospital",
            value: "St. Jude Children's Research Hospital",
        },
        { label: 'March of Dimes', value: 'March of Dimes' },
        { label: "Alzheimer's Association", value: "Alzheimer's Association" },
        {
            label: 'American Heart Association',
            value: 'American Heart Association',
        },
        {
            label: 'American Diabetes Association',
            value: 'American Diabetes Association',
        },
        {
            label: 'National Multiple Sclerosis Society',
            value: 'National Multiple Sclerosis Society',
        },
        { label: "Parkinson's Foundation", value: "Parkinson's Foundation" },
        { label: 'Susan G. Komen', value: 'Susan G. Komen' },
        {
            label: 'Cystic Fibrosis Foundation',
            value: 'Cystic Fibrosis Foundation',
        },
        {
            label: 'Leukemia & Lymphoma Society',
            value: 'Leukemia & Lymphoma Society',
        },
        { label: 'Special Olympics', value: 'Special Olympics' },
        {
            label: 'Best Friends Animal Society',
            value: 'Best Friends Animal Society',
        },
        {
            label: 'ASPCA Animal Poison Control',
            value: 'ASPCA Animal Poison Control',
        },
        { label: 'Goodwill Industries', value: 'Goodwill Industries' },
        { label: 'The Trevor Project', value: 'The Trevor Project' },
        { label: 'Crisis Text Line', value: 'Crisis Text Line' },
        {
            label: 'National Alliance on Mental Illness',
            value: 'National Alliance on Mental Illness',
        },
        { label: 'Mental Health America', value: 'Mental Health America' },
        { label: 'Smithsonian', value: 'Smithsonian' },
        {
            label: 'National Geographic Society',
            value: 'National Geographic Society',
        },
        { label: 'The Nature Conservancy', value: 'The Nature Conservancy' },
        { label: 'Sierra Club', value: 'Sierra Club' },
        {
            label: 'Environmental Defense Fund',
            value: 'Environmental Defense Fund',
        },
        { label: 'Greenpeace', value: 'Greenpeace' },
        { label: 'Oceana', value: 'Oceana' },
        { label: 'Rainforest Alliance', value: 'Rainforest Alliance' },
        { label: 'Wilderness America', value: 'Wilderness America' },
        { label: 'The Ocean Cleanup', value: 'The Ocean Cleanup' },
        { label: 'Trees, Water & People', value: 'Trees, Water & People' },
        { label: 'Doctors of the World', value: 'Doctors of the World' },
        { label: 'Project HOPE', value: 'Project HOPE' },
        {
            label: 'Heart to Heart International',
            value: 'Heart to Heart International',
        },
        { label: 'MAP International', value: 'MAP International' },
        { label: 'Hope For The Warriors', value: 'Hope For The Warriors' },
        { label: 'Wounded Warrior Project', value: 'Wounded Warrior Project' },
        { label: 'Fisher House Foundation', value: 'Fisher House Foundation' },
        {
            label: 'Marine Toys for Tots Foundation',
            value: 'Marine Toys for Tots Foundation',
        },
        { label: 'American Legion', value: 'American Legion' },
        { label: 'Vets4Warriors', value: 'Vets4Warriors' },
        { label: 'Folds of Honor', value: 'Folds of Honor' },
        { label: 'Scholarship America', value: 'Scholarship America' },
        { label: 'Points of Light', value: 'Points of Light' },
        { label: 'United Way', value: 'United Way' },
        { label: 'Volunteers of America', value: 'Volunteers of America' },
        {
            label: 'American Legion Auxiliary',
            value: 'American Legion Auxiliary',
        },
        { label: 'Rotary International', value: 'Rotary International' },
        {
            label: 'Lions Club International',
            value: 'Lions Club International',
        },
        { label: 'Kiwanis International', value: 'Kiwanis International' },
        { label: 'Junior Achievement', value: 'Junior Achievement' },
        {
            label: 'Big Brothers Big Sisters',
            value: 'Big Brothers Big Sisters',
        },
        {
            label: 'Boys & Girls Clubs of America',
            value: 'Boys & Girls Clubs of America',
        },
        { label: 'The Innocence Project', value: 'The Innocence Project' },
        {
            label: 'NAACP Legal Defense Fund',
            value: 'NAACP Legal Defense Fund',
        },
        { label: 'ACLU', value: 'ACLU' },
        { label: 'Human Rights Campaign', value: 'Human Rights Campaign' },
        { label: 'Amnesty International', value: 'Amnesty International' },
        { label: 'Human Rights Watch', value: 'Human Rights Watch' },
        {
            label: 'Reporters Without Borders',
            value: 'Reporters Without Borders',
        },
        {
            label: 'International Federation of Red Cross',
            value: 'International Federation of Red Cross',
        },
        { label: 'Partners In Health', value: 'Partners In Health' },
        { label: 'PEPFAR', value: 'PEPFAR' },
        { label: 'The Carter Center', value: 'The Carter Center' },
    ].sort((a, b) => a.label.localeCompare(b.label))

    return {
        organizations,
    }
}
